name: pa11y-ci

on:
  pull_request:
    branches: [ "main" ]

jobs:
  pa11y-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Build & Run Application
        run: |
          npm ci
          npm run build --if-present
          npm start & npx wait-on http://127.0.0.1:3000
          npm run test-pa11y
